version: '3.8'
services:
  client_portal-web:
    build:
      dockerfile: Dockerfile
      context: ./
      target: local
    image: node:alpine
    container_name: client_portal-web
    ports:
      - 80:80
    volumes:
      - ./:/app
      - /app/node_modules
